### ISSUE TITLE
File uploads?

### ISSUE THREAD

**Issue by pchristen** [dlrep/dlrep#57]
@ozgurakgun How do I upload files (like CSV data set) into the dlrep repo?

I get the following error message:

---

Uploads are disabled.

File uploads require push access to this repository.
----
I think we need to allow file upload as most people will want to use the Web interface.
Thanks, Peter

**Comment by ozgurakgun** [comment]
Normally, you should be uploading to your fork and creating a pull request. Are you trying to upload directly to the main repository?

I am not sure if that is desirable, since it can potentially break the build. Or we end up hosting content we know nothing about, potentially with the wrong license, etc.

**Comment by pchristen** [comment]
Thanks Oz, I do understand, but how do we want people to submit their data sets? Imagine for example a social scientist who wants to contribute a data set..? Do we need a Web submission form?

**Comment by ozgurakgun** [comment]
Automating this via a web based form is probably the way to go, that's a good idea. We can think of a few use cases like this and provide forms which do the right thing for those.

**Comment by ozgurakgun** [comment]
I think #62 answers this, but I agree the web form can make life easier. Closing the issue.

**Comment by drummer74** [comment]
Для загрузки файлов требуется push-доступ к этому репозиторию.
